const levels=[
{id:'troc',title:'Le troc',situation:'Tu possèdes 10 pommes et tu veux obtenir un poulet auprès d’un voisin.',problem:'Que peux-tu faire pour obtenir le poulet ?',choices:[['Proposer des pommes en échange','Le voisin accepte si les pommes ont une valeur pour lui.'],['Attendre sans rien proposer','Sans échange, aucun des deux produits ne change de propriétaire.'],['Prendre le poulet','Prendre sans accord n’est pas une vente ni un échange.']],concepts:['produit','besoin','échange','achat','vente','valeur'],next:'La double coïncidence des besoins'},
{id:'coincidence',title:'Le problème du troc',situation:'Ton voisin possède le poulet mais ne veut pas de pommes. Toi, tu veux le poulet.',problem:'Comment rendre l’échange possible ?',choices:[['Chercher quelqu’un qui veut tes pommes','Tu dois trouver une contrepartie que les deux parties acceptent.'],['Donner encore plus de pommes','Cela ne résout pas le problème si le voisin ne valorise pas les pommes.'],['Abandonner le principe d’échange','Le problème vient du moyen d’échange, pas de l’idée d’échanger.']],concepts:['double coïncidence des besoins','utilité','valeur'],next:'Un intermédiaire accepté par tous'},
{id:'monnaie',title:'La monnaie',situation:'Le village décide d’utiliser une même unité acceptée par tous pour faciliter les échanges.',problem:'Pourquoi cette unité rend-elle les échanges plus simples ?',choices:[['Elle sert d’intermédiaire d’échange','Tu peux vendre tes pommes puis utiliser la monnaie pour acheter le poulet.'],['Elle crée automatiquement des produits','La monnaie facilite l’échange mais ne produit pas elle-même les biens.'],['Elle garantit que tout le monde est riche','Posséder de la monnaie ne signifie pas posséder davantage de richesse réelle.']],concepts:['monnaie','moyen d’échange','unité de compte','réserve de valeur'],next:'Comparer les biens avec un prix'},
{id:'prix',title:'Le prix',situation:'Une pomme coûte 1 € et un poulet coûte 5 €. Tu peux maintenant comparer les biens avec une même unité.',problem:'À quoi sert le prix ?',choices:[['Exprimer une valeur d’échange en monnaie','Le prix permet de comparer et d’échanger des biens dans une unité commune.'],['Mesurer exactement la valeur de toute chose','Le prix est un signal monétaire, pas une mesure parfaite de la valeur subjective.'],['Garantir que le prix ne changera jamais','Les prix peuvent varier selon l’offre, la demande et d’autres facteurs.']],concepts:['prix','offre','demande','rareté','valeur'],next:'Que faire avec une monnaie non dépensée ?'},
{id:'epargne',title:'L’épargne',situation:'Tu gagnes 2 000 € et n’as besoin que de 1 700 € aujourd’hui.',problem:'Que peux-tu faire avec les 300 € restants ?',choices:[['Les épargner','Tu reportes une partie de ton pouvoir d’achat vers le futur.'],['Les considérer comme une richesse produite','L’épargne est un actif monétaire, pas une production supplémentaire.'],['Les dépenser obligatoirement','Il n’est pas nécessaire de consommer immédiatement tout son revenu.']],concepts:['revenu','épargne','consommation','patrimoine','pouvoir d’achat'],next:'Obtenir aujourd’hui une somme à rembourser demain'},
{id:'credit',title:'Le crédit',situation:'Tu veux acheter une maison maintenant mais tu n’as pas encore toute la somme.',problem:'Pourquoi une banque pourrait-elle te prêter de l’argent ?',choices:[['Parce que tu promets de rembourser selon un contrat','Le crédit transfère du pouvoir d’achat dans le temps et implique un risque.'],['Parce qu’un prêt est toujours gratuit','Le prêteur supporte un coût et un risque.'],['Parce que la dette disparaît après l’achat','La dette reste une obligation jusqu’au remboursement.']],concepts:['crédit','dette','contrat','risque','temps'],next:'Pourquoi payer davantage que le capital emprunté ?'},
{id:'interet',title:'L’intérêt',situation:'La banque prête 80 000 € et demande le remboursement du capital avec un supplément.',problem:'Pourquoi ce supplément existe-t-il ?',choices:[['Rémunérer le temps, le financement et le risque','Le taux d’intérêt participe au prix du crédit.'],['Parce que la monnaie devient automatiquement plus précieuse','L’intérêt ne garantit pas une hausse générale de la valeur de la monnaie.'],['Parce que toute dette doit doubler','Le coût dépend notamment du taux, de la durée et des conditions.']],concepts:['intérêt','taux','capital','durée','risque'],next:'Que se passe-t-il quand le pouvoir d’achat de la monnaie change ?'},
{id:'inflation',title:'L’inflation',situation:'Ton salaire reste à 2 000 €, mais le panier de biens que tu achètes passe de 1 700 € à 1 850 €.',problem:'Qu’est-ce qui a changé pour toi ?',choices:[['Ton pouvoir d’achat a diminué','Avec le même revenu nominal, tu peux acheter moins de biens.'],['Tu es automatiquement devenu plus pauvre en patrimoine','Le pouvoir d’achat et le patrimoine sont liés mais ne sont pas identiques.'],['Un seul prix suffit à définir l’inflation','L’inflation désigne une hausse générale et durable du niveau des prix.']],concepts:['inflation','niveau général des prix','pouvoir d’achat','revenu nominal','revenu réel'],next:'Faire travailler une épargne avec un rendement et un risque'},
{id:'investissement',title:'L’investissement',situation:'Tu disposes de 10 000 € et envisages un placement pouvant rapporter davantage mais avec un risque de perte.',problem:'Quel arbitrage dois-tu comprendre ?',choices:[['Risque contre rendement potentiel','Un rendement potentiel plus élevé peut s’accompagner d’un risque plus important.'],['Rendement élevé sans aucune incertitude','Il n’existe pas de rendement élevé garanti par principe.'],['Investissement = consommation','L’investissement vise généralement un rendement ou une capacité future.']],concepts:['investissement','rendement','risque','diversification','arbitrage'],next:'Synthétiser le modèle monétaire'}
];
let i=0,graph=new Set(),start=performance.now(),events=[];
const $=id=>document.getElementById(id); function render(){const l=levels[i];$('level').textContent=`NIVEAU ${i+1} / ${levels.length}`;$('title').textContent=l.title;$('situation').textContent=l.situation;$('problem').textContent=l.problem;$('choices').innerHTML=l.choices.map((c,n)=>`<button data-n="${n}">${c[0]}</button>`).join('');$('feedback').hidden=true;$('assessment').hidden=true;$('progress').textContent=`${Math.round(i/levels.length*100)} %`;document.querySelectorAll('#choices button').forEach(b=>b.onclick=()=>feedback(+b.dataset.n));drawGraph()}
function feedback(n){const l=levels[i],choice=l.choices[n];l.concepts.forEach(c=>graph.add(c));events.push({level:l.id,choice:n,time:Math.round(performance.now()-start)});$('feedbackTitle').textContent=n===0?'Conséquence comprise':'Pourquoi ce choix est-il limité ?';$('feedbackText').textContent=choice[1];$('conceptList').innerHTML=l.concepts.map(c=>`<span class="concept">${c}</span>`).join('');$('previous').textContent=i?'Les concepts précédents restent actifs dans ton modèle.':'Point de départ : produire et échanger des biens.';$('next').textContent=l.next;$('feedback').hidden=false;$('choices').innerHTML='';drawGraph()}
$('continue').onclick=()=>{i++;if(i<levels.length)render();else{$('feedback').hidden=true;$('assessment').hidden=false;$('progress').textContent='100 %';drawGraph()}};
$('finish').onclick=()=>{const a=$('answer').value.trim();const keywords=['prix','pouvoir d’achat','inflation','prix','monnaie'];const score=keywords.filter(k=>a.toLowerCase().includes(k)).length;localStorage.setItem('cognitorium-money-poc',JSON.stringify({events,graph:[...graph],transferScore:score,answer:a}));$('result').textContent=`PoC terminé. Concepts construits : ${graph.size}. Indice lexical de transfert : ${score}/${keywords.length}. Les données sont conservées localement.`};
function drawGraph(){$('graph').innerHTML=[...graph].map((c,j)=>`<span class="node ${j>=graph.size- levels[i]?.concepts.length?'new':''}">${c}</span>`).join('')||'<p>Les concepts apparaîtront ici au fil de tes décisions.</p>'}render();
